---
title: "__Experiment 2:__ Data modelling"
author: "Massimiliano Canzi | `massimiliano.canzi@uni-konstanz.de`"
date: "Last modified: _20/02/2021_"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r, message = F}
library(emmeans) # Pair-wise contrasts
library(lme4) # Linear Mixed Effect Models
library(lmerTest) # KR F-test ANOVA tables
library(magrittr) # For %<>%
library(tidyverse) # For everything else! 
```

## Data pre-processing

```{r readr.1, message = FALSE}
ERP <- read_csv("../data/EXP2.lmer.csv") %>%
  filter(Block == "ATT") %>%
  mutate(Subj = as.factor(Subj)) %>%
  filter(time >= 0 & time <= 700) %>%
  gather(electrode, amplitude, Fp1:T8, factor_key = TRUE) %>%
  mutate(time = as.numeric(as.character(format(round(time, 0), nsmall = 0))),
         Block = as.factor(Block))

names(ERP) <- c("subject", "block", "condition", "time", "electrode", "amplitude")
```

```{r readr.2, message = FALSE}
ERP %<>% mutate(time = as.factor(time), subject = as.factor(subject)) %>%
  group_by(subject, block, condition, electrode, time) %>% 
  summarise(amplitude.mean = mean(amplitude),) %>% 
  ungroup() %>% mutate(time = as.numeric(as.character(time)), 
                       amplitude.mean = as.numeric(amplitude.mean), 
                       electrode = as.factor(electrode)) %>%
  filter(amplitude.mean <= 20 & amplitude.mean >= -20) %>%
  mutate(amplitude.mean = as.numeric(format(round(amplitude.mean, 2), nsmall = 2)))
```

## Model preparation

```{r summarised.data.function, message = F}
summarised.data <- function(TP1, TP2, type = "main") {

  if (type == "main") { 
    lmer <- ERP %>% filter(condition == "control" | condition == "target") }
  if (type == "syllable") {
    lmer <- ERP %>% filter(condition != "control" & condition != "target") %>%
      mutate(condition = as.factor(condition))}
  
  lmer.data <- left_join(lmer %>%
    filter(time >= TP1) %>%
    filter(time <= TP2) %>%
      group_by(subject, block, condition, electrode) %>%
      summarise(amplitude = mean(amplitude.mean),) %>% ungroup,
    read.csv("../resources/lmer_electrodes.csv", 
                        sep = ";"), by = "electrode") %>% 
    rename(hemisphere = side) %>%
    filter(hemisphere != "none") %>%
    select(subject, hemisphere, region, condition, amplitude) %>%
    group_by(subject, condition) %>%
    mutate(subject = as.factor(paste0("S", subject))) %>%
    mutate_if(is.character, as.factor)
  
  return(lmer.data) }
```

```{r control.REML, message = F}
control <- lmerControl(check.conv.singular = "ignore")
REML = TRUE
```

```{r head, message = F}
head(summarised.data(75, 100, type = "syllable"))
```

## LMEM: 75-100 ms

```{r model.75.100, message = F}
model.75.100 <- summarised.data(75, 100) %>% 
  lmer(formula = amplitude ~ condition * region + hemisphere + (1 | subject), 
       REML = TRUE, control = control)
```

```{r Anova.model.7.100, message = F}
anova(model.75.100, type = "III", ddf = "Kenward-Roger")
emmeans(model.75.100, pairwise ~ condition | region)
```

## LMEM: 160-210 ms

```{r model.160.210, message = F}
model.160.210 <- summarised.data(160, 210) %>% 
  lmer(formula = amplitude ~ condition * hemisphere + region + (1 | subject), 
       control = control, REML = REML)
```

```{r Anova.model.160.210, message = F}
anova(model.160.210, type = "III", ddf = "Kenward-Roger")
emmeans(model.160.210, pairwise ~ condition | hemisphere)
``` 

## LMEM: 250-290 ms

```{r model.250.290, message = F}
model.250.290 <- summarised.data(250, 290) %>% 
  lmer(formula = amplitude ~ condition * region + hemisphere + (1 | subject), 
       control = control, REML = REML)
```

```{r Anova.model.250.290, message = F}
anova(model.250.290, type = "III", ddf = "Kenward-Roger")
emmeans(model.250.290, pairwise ~ condition | region)
```

## LMEM: 280-320 ms

```{r model.280.320, message = F}
model.280.320 <- summarised.data(280, 320) %>%
  lmer(formula = amplitude ~ condition * region + region * hemisphere + 
         (1 | subject), 
       control = control, REML = REML)
```

```{r Anova.model.280.320, message = F}
anova(model.280.320, type = "III", ddf = "Kenward-Roger")
emmeans(model.280.320, pairwise ~ condition | region)
```

## LM: 575-625 ms

```{r model.575.625, message = F}
model.575.625 <- summarised.data(575, 625) %>%
  lmer(formula = amplitude ~ condition * region + hemisphere + (1 | subject), 
       control = control, REML = REML)
```

```{r Anova.model.575.625, message = F}
anova(model.575.625, type = "III", ddf = "Kenward-Roger")
emmeans(model.575.625, pairwise ~ condition | region)
```

## Syllable LMEM: 75-100

```{r model.75.100.S, message = F}
model.75.100 <- summarised.data(75, 100, type = "syllable") %>% 
  lmer(formula = amplitude ~ condition * region + hemisphere + (1 | subject), 
       REML = TRUE, control = control)
```

```{r Anova.model.75.100.S, message = F}
anova(model.75.100, type = "III", ddf = "Kenward-Roger")
emmeans(model.75.100, pairwise ~ condition | region)
```

