---
title: "ERP_exploration"
author: "Massimiliano Canzi"
date: "27/03/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(ggpubr)
library(devtools)
library(tidyverse)
library(ERP)
library(viridis)
library(akima)
library(scales)
library(effects)
library(reshape2)
library(lmerTest)
library(lme4)

matplotlibRdBu_r <- colorRampPalette(c("#053061","#4694C4","#F6F6F6","#E7886C","#67001F"),interpolate = "spline")
```

```{r, warnings = FALSE}
ERP <- rbind(read.csv("ERP_pt1.csv"), read.csv("ERP_pt2.csv"), 
             read.csv("ERP_pt3.csv"), read.csv("ERP_pt4.csv"), 
             read.csv("1ERP_pt1.csv"), read.csv("1ERP_pt2.csv"),
             read.csv("1ERP_pt3.csv"), read.csv("1ERP_pt4.csv")) %>% 
            filter_if(~is.numeric(.), all_vars(!is.infinite(.)))

ERP <- ERP[(ERP$time >= -100) & (ERP$time <= 500),]
ERP <- gather(ERP, electrode, amplitude, Fp1:PO4, factor_key=TRUE)
ERP$time <- format(round(ERP$time, 0), nsmall = 0) 
ERP$time <- as.numeric(as.character(ERP$time))
names(ERP) <- c("subject", "block", "condition", "time", "electrode", "amplitude")

electrodeLocs <- read_delim("https://raw.githubusercontent.com/craddm/ExploringERPs/master/biosemi70elecs.loc", "\t",
  escape_double = FALSE,
  col_names = c("chanNo","theta","radius", "electrode"),
  trim_ws = TRUE)

ERP$electrode <- as.factor(ERP$electrode)
ERP$subject <- as.factor(ERP$subject)
ERP$BLOCK <- as.factor(ERP$block)

ERP$time <- as.factor(ERP$time)
ERP <- ERP %>% group_by(subject, block, condition, electrode, time) %>% 
  summarise(amplitude.mean=mean(amplitude),) %>% 
  ungroup  
ERP$time <- as.numeric(as.character(ERP$time))

ERP <- filter(ERP, subject != "7")
ERP <- filter(ERP, subject != "13")
ERP <- filter(ERP, subject != "1")

ERP_testing <- filter(ERP, time %% 2 == 0)
ERP_testing$time <- as.double(ERP_testing$time)
ERP_testing$amplitude.mean <- as.double(ERP_testing$amplitude.mean)

electrodeLocs$radianTheta <- pi/180*electrodeLocs$theta
electrodeLocs <- electrodeLocs %>%
  mutate(x = .$radius*sin(.$radianTheta), y = .$radius*cos(.$radianTheta))

ERP <- ERP %>% left_join(electrodeLocs, by = "electrode")
#ERP <- filter(ERP, subject != "4" & subject != "6" & subject != "7" & subject != "104")

ERP$amplitude.mean <- as.numeric(ERP$amplitude.mean)
ERP$electrode <- as.factor(ERP$electrode)

ERP <- filter(ERP, amplitude.mean <= 7 & amplitude.mean >= -7)
ERP$amplitude.mean <- format(round(ERP$amplitude.mean, 2), nsmall = 2)
ERP$amplitude.mean <- as.numeric(ERP$amplitude.mean)

ERP_123 = c("steelblue", "palevioletred1", "limegreen")
sign_col <- "indianred"
ERP_CTB = c("skyblue4", "palegreen3")
ERP_TTB = c("palevioletred1", "palegreen3")

ERP_scaled <- ERP %>% 
  group_by(subject, block) %>%
  mutate(amplitude.mean = scale(amplitude.mean)) %>%
  ungroup()

ERP_testing_scaled <- ERP_testing %>%
  group_by(subject, block) %>%
  mutate(amplitude.mean = scale(amplitude.mean)) %>%
  ungroup()
```

```{r}
calculate_average_erp <- function(t1 = 200, t2 = 200, type = "CT2", elec = electrodes) {

  ERP_scaled <- ERP %>% 
    group_by(block, subject, condition, electrode) %>%
    mutate(amplitude.mean = scale(amplitude.mean)) %>%
    ungroup()
  
  ERP_ave <- ERP_scaled %>% 
    filter(time >= t1) %>% 
    filter(time <= t2) %>%
    group_by(block, subject, condition, electrode) %>%
    mutate(mean_amp = mean(amplitude.mean)) %>%
    ungroup() %>%
    filter (time == t1 + (t2-t1) / 2) %>%
    filter(electrode %in% electrodes) %>%
    filter(condition == "control" | condition == "target")

  if (type == "CT2") {
      
    ERP_ave <- ERP_ave %>%
      filter(block == "ATT") }
  
  else if (type == "CT1") {
      
    ERP_ave <- ERP_ave %>%
      filter(block != "ATT") %>%
      filter(block != "BSL") }

  bplot_ave <- ggplot(ERP_ave, aes(condition, mean_amp, fill = condition)) +
    geom_boxplot() +
    geom_jitter() +
    facet_wrap(ncol = 2, facets = ERP_ave$electrode) + 
    ylim(-1.5, 1.5) + 
    xlab("Experimental Condition") +
    ylab(paste("Normalised Average Ampltiude between ", t1, " and ", t2, " ms")) +
    scale_fill_manual(values = c("indianred3", "slategray3"), labels = c("Standard", "Manipulated")) +
    scale_color_viridis_d() +
    theme_minimal()
  
  return(bplot_ave) }

electrodes <- c("AF7", "AF3", "AF4", "AF8", "F7", "F3", "F4", "F8")
boxplots250 <- calculate_average_erp(t1 = 225, t2 = 275, elec = electrodes, type = "CT2")
ggsave("./pictures/boxplots250.png", boxplots250, width = 9, height = 10, dpi = "print")

electrodes <- c("AF7", "AF3", "AF4", "AF8", "F7", "F3", "F4", "F8")
boxplots100 <- calculate_average_erp(t1 = 80, t2 = 120, elec = electrodes, type = "CT2")
ggsave("./pictures/boxplots100.png", boxplots100, width = 9, height = 10, dpi = "print")
```

```{r}

t1 = 75
t2 = 125

significant <- lapply(electrodes, function (electrodes) {
  
  ERP_ave <- ERP_scaled %>% 
    filter(time >= t1) %>% 
    filter(time <= t2) %>%
    group_by(block, subject, condition, electrode) %>%
    mutate(mean_amp = mean(amplitude.mean)) %>%
    ungroup() %>%
    filter (time == t1 + (t2-t1) / 2) %>%
    filter(electrode == electrodes) %>%
    filter(condition == "control" | condition == "target") %>%
    filter(block == "ATT")

  model <- lm(mean_amp ~ condition, data = ERP_ave)
  
    if (class(model) != "lm") stop("Not an object of class 'lm' ")
    f <- summary(model)$fstatistic
    p <- pf(f[1],f[2],f[3],lower.tail=F)
    attributes(p) <- NULL
    return(p) } )

significant
```

```{r}
ERP_CT <- filter(ERP_testing_scaled, block == "ATT") %>% 
  filter(condition != "first_syllable") %>% 
  filter(condition != "second_syllable") %>%
  filter(condition != "third_syllable")

ERP_CTest <- filter(ERP_testing_scaled, block == "ATT") %>%
  filter(condition != "first_syllable") %>% 
  filter(condition != "second_syllable") %>%
  filter(condition != "third_syllable")

ERP_1CT <- filter(ERP_testing_scaled, block == "ATT") %>%
  filter(condition != "second_syllable") %>% 
  filter(condition != "third_syllable") 

ERP_S <- filter(ERP_testing_scaled, block == "ATT") %>%
  filter(condition != "control") %>%
  filter(condition != "target")

ERP_S12 <- filter(ERP_testing_scaled, block == "ATT") %>%
  filter(condition != "third_syllable") %>%
  filter(condition != "control") %>%
  filter(condition != "target")

ERP_EXP12 <- filter(ERP_testing_scaled, block != "BSL") %>%
  filter(condition == "target")
```


```{r}
significance <- function(t = "CT", elec = "") {
  
  if (t == "CT") {
  
    ERP_testelec <- filter(ERP_CTest, electrode == elec)
    ERP_testwide <- spread(ERP_CTest, time, amplitude.mean)
  
    TERP <- ERP_testwide[(ERP_testwide$electrode == elec), 5:305]
    cov.TERP = ERP_testwide[(ERP_testwide$electrode == elec), 1:4]
    cov.TERP = droplevels(cov.TERP)
    design <- model.matrix(~C(subject,sum) + condition, data = cov.TERP)
    design0 <- model.matrix(~C(subject,sum), data = cov.TERP) }
  
  else if (t == "S") {
    
    ERP_testelec <- filter(ERP_S12, electrode == elec)
    ERP_testwide <- spread(ERP_S12, time, amplitude.mean)
  
    TERP <- ERP_testwide[(ERP_testwide$electrode == elec), 5:305]
    cov.TERP = ERP_testwide[(ERP_testwide$electrode == elec), 1:4]
    cov.TERP = droplevels(cov.TERP)
    design <- model.matrix(~C(subject,sum) + condition, data = cov.TERP)
    design0 <- model.matrix(~C(subject,sum), data = cov.TERP) }
  
  else if (t == "EXP12") {
    
    ERP_testelec <- filter(ERP_EXP12, electrode == elec)
    ERP_testwide <- spread(ERP_EXP12, time, amplitude.mean)
  
    TERP <- ERP_testwide[(ERP_testwide$electrode == elec), 5:305]
    cov.TERP = ERP_testwide[(ERP_testwide$electrode == elec), 1:4]
    cov.TERP = droplevels(cov.TERP)
    design <- model.matrix(~C(subject,sum) + block, data = cov.TERP)
    design0 <- model.matrix(~C(subject,sum), data = cov.TERP) }

  fabh <- erpfatest(TERP, design, design0, nbf = 6) 
  
  return(fabh$significant) }
```

```{r}
ERP_lol <- filter(ERP_testing, block == "ATT")

lol <- ggplot(ERP_lol, aes(time, amplitude.mean, color = electrode)) +
  geom_line() + 
  facet_wrap(facets = "subject")

lol
```


```{r}
bae <- function(elec = "Cz", type = "CT", labels = FALSE, significant = TRUE) {
  
  if (type == "CT") {
  
    ERP_gae <- filter(ERP_CT, electrode == elec) 
    colz <- c("indianred2", "steelblue")
    labelz <- c("Standard", "Manipulated")
    ind_v <- ERP_gae$condition }
  
  else if (type == "S") {
    
    ERP_gae <- filter(ERP_S, electrode == elec) 
    colz <- c("violetred3", "palegreen4", "mediumorchid4")
    labelz <- c("First syllable", "Second syllable", "Third syllable")
    ind_v <- ERP_gae$condition }
    
  else if (type == "1CT") {
      
    ERP_gae <- filter(ERP_1CT, electrode == elec) 
    colz <- c("indianred2", "violetred3", "steelblue")
    labelz <- c("Control", "First Syllable", "Target") 
    ind_v <- ERP_gae$condition }
  
  else if (type == "EXP12") {

    ERP_gae <- filter(ERP_EXP12, electrode == elec)
    colz <- c("steelblue", "indianred")
    labelz <- c("Experiment 2", "Experiment 1")
    ind_v <- ERP_gae$block }

  if (labels == TRUE) {
  
  gap <- ggplot(ERP_gae, aes(time, amplitude.mean, colour = ind_v)) +
      stat_summary(fun.y = mean, geom = "line", size = 0.5, na.rm = TRUE, show.legend = TRUE) +
      stat_smooth(geom='line', alpha = 0.3, size = 2, se = FALSE) +
      labs(x = "Time (ms)", y = "Amplitude (mV)", colour = "") +
      xlim(c(-100, 350)) +
      theme_minimal() + 
      #xlim(c(-100, 350)) +
      geom_vline(xintercept = 0, linetype = "dashed" ) +
      geom_hline(yintercept = 0, linetype = "dashed") +
      scale_colour_manual(values = colz, labels = labelz) +
      ggtitle(elec) }
  
  else {

  gap <- ggplot(ERP_gae, aes(time, amplitude.mean, colour = ind_v)) +
      stat_summary(fun.y = mean, geom = "line", size = 0.5, na.rm = TRUE, show.legend = TRUE) +
      stat_smooth(geom='line', alpha = 0.3, size = 2, se = FALSE) +
      labs(x = "", y = "") +
      xlim(c(-100, 350)) +
      geom_vline(xintercept = 0, linetype = "dashed" ) +
      geom_hline(yintercept = 0, linetype = "dashed") +
      scale_colour_manual(values = colz, labels = labelz) +
      theme_minimal() +
      ggtitle(elec) }
  
  if (significant == TRUE) {
    
    spts <- significance(t = type, elec) 
    spts1 <- as.data.frame(spts)
    
    if (length(spts) != 0) {
      gap = gap + geom_point(data = spts1, mapping = aes(x = spts, y = -0.3), size = 3, shape = 20, 
      color = sign_col) } }
  
  return(gap) }
```

MANIPULATED VS STANDARD

```{r, include = FALSE}
noafa_af <- ggarrange(
  bae(elec = "AF7", labels = TRUE, significant = FALSE),
  bae(elec = "AF3", significant = FALSE),
  bae(elec = "AF4", significant = FALSE),
  bae(elec = "AF8", significant = FALSE),
  bae(elec = "F7", significant = FALSE),
  bae(elec = "F3", significant = FALSE),
  bae(elec = "F4", significant = FALSE),
  bae(elec = "F8", significant = FALSE),
  nrow = 2, ncol = 4, 
  common.legend =  TRUE)

noafa_af
#ggsave("./pictures/noafa_af.png", noafa_af, width = 11, height = 7, dpi = "print")

noafa_fc <- ggarrange(
  bae(elec = "FT7", labels = TRUE, significant = FALSE),
  bae(elec = "FC3", significant = FALSE),
  bae(elec = "FC4", significant = FALSE),
  bae(elec = "FT8", significant = FALSE),
  bae(elec = "T7", significant = FALSE),
  bae(elec = "C3", significant = FALSE),
  bae(elec = "C4", significant = FALSE),
  bae(elec = "T8", significant = FALSE),
  nrow = 2, ncol = 4, 
  common.legend =  TRUE)

noafa_fc
#ggsave("./pictures/noafa_fc.png", noafa_fc, width = 11, height = 7, dpi = "print")

anterior_frontal <- ggarrange(
  bae(elec = "AF7", labels = TRUE),
  bae(elec = "AF8"),
  bae(elec = "F7"),
  bae(elec = "F8"),
  bae(elec = "F3"),
  bae(elec = "F4"),
  nrow = 3, ncol = 2,
  common.legend =  TRUE)

anterior_frontal
#ggsave("./pictures/anterior_frontal.png", anterior_frontal, width = 9, height = 10, dpi = "print")

fronto_central <- ggarrange( 
  bae(elec = "FT7", labels = TRUE),
  bae(elec = "FT8"),
  bae(elec = "T7"),
  bae(elec = "T8"),
  bae(elec = "C3"),
  bae(elec = "C4"),
  nrow = 3, ncol = 2,
  common.legend =  TRUE)

fronto_central
#ggsave("./pictures/fronto_central.png", fronto_central, width = 9, height = 10, dpi = "print")
```

FIRST, SECOND AND THIRD SYLLABLE

```{r, include = FALSE}
noafa123_af <- ggarrange(
  bae(elec = "AF7", type = "S", labels = TRUE, significant = FALSE),
  bae(elec = "AF3", type = "S", significant = FALSE),
  bae(elec = "AF4", type = "S", significant = FALSE),
  bae(elec = "AF8", type = "S", significant = FALSE),
  bae(elec = "F7", type = "S", significant = FALSE),
  bae(elec = "F3", type = "S", significant = FALSE),
  bae(elec = "F4", type = "S", significant = FALSE),
  bae(elec = "F8", type = "S", significant = FALSE),
  nrow = 2, ncol = 4, 
  common.legend =  TRUE)

ggsave("./pictures/noafa123_af.png", noafa123_af, width = 11, height = 7, dpi = "print")

noafa123_fc <- ggarrange(
  bae(elec = "FT7", type = "S", labels = TRUE, significant = FALSE),
  bae(elec = "FC3", type = "S", significant = FALSE),
  bae(elec = "FC4", type = "S", significant = FALSE),
  bae(elec = "FT8", type = "S", significant = FALSE),
  bae(elec = "T7", type = "S", significant = FALSE),
  bae(elec = "C3", type = "S", significant = FALSE),
  bae(elec = "C4", type = "S", significant = FALSE),
  bae(elec = "T8", type = "S", significant = FALSE),
  nrow = 2, ncol = 4, 
  common.legend =  TRUE)

ggsave("./pictures/noafa123_fc.png", noafa123_fc, width = 11, height = 7, dpi = "print")

anterior_frontal123 <- ggarrange(
  bae(elec = "AF7", type = "S", labels = TRUE),
  bae(elec = "AF8", type = "S"),
  bae(elec = "F7", type = "S"),
  bae(elec = "F8", type = "S"),
  bae(elec = "F3", type = "S"),
  bae(elec = "F4", type = "S"),
  nrow = 3, ncol = 2,
  common.legend =  TRUE)

anterior_frontal123
#ggsave("./pictures/anterior_frontal123.png", anterior_frontal123, width = 9, height = 10, dpi = "print")

fronto_central123 <- ggarrange( 
  bae(elec = "FT7", type = "S", labels = TRUE),
  bae(elec = "FT8", type = "S"),
  bae(elec = "T7", type = "S"),
  bae(elec = "T8", type = "S"),
  bae(elec = "C3", type = "S"),
  bae(elec = "C4", type = "S"),
  nrow = 3, ncol = 2,
  common.legend =  TRUE)

fronto_central123
#ggsave("./pictures/fronto_central123.png", fronto_central123, width = 9, height = 10, dpi = "print")
```

FIRST SYLLABLE, MANIPULATED AND STANDARD

```{r}
noafa1CT_af <- ggarrange(
  bae(elec = "AF7", type = "1CT", labels = TRUE, significant = FALSE),
  bae(elec = "AF3", type = "1CT", significant = FALSE),
  bae(elec = "AF4", type = "1CT", significant = FALSE),
  bae(elec = "AF8", type = "1CT", significant = FALSE),
  bae(elec = "F7", type = "1CT", significant = FALSE),
  bae(elec = "F3", type = "1CT", significant = FALSE),
  bae(elec = "F4", type = "1CT", significant = FALSE),
  bae(elec = "F8", type = "1CT", significant = FALSE),
  nrow = 2, ncol = 4, 
  common.legend =  TRUE)

ggsave("./pictures/noafa1CT_af.png", noafa1CT_af, width = 11, height = 7, dpi = "print")

noafa1CT_fc <- ggarrange(
  bae(elec = "FT7", type = "1CT", labels = TRUE, significant = FALSE),
  bae(elec = "FC3", type = "1CT", significant = FALSE),
  bae(elec = "FC4", type = "1CT", significant = FALSE),
  bae(elec = "FT8", type = "1CT", significant = FALSE),
  bae(elec = "T7", type = "1CT", significant = FALSE),
  bae(elec = "C3", type = "1CT", significant = FALSE),
  bae(elec = "C4", type = "1CT", significant = FALSE),
  bae(elec = "T8", type = "1CT", significant = FALSE),
  nrow = 2, ncol = 4, 
  common.legend =  TRUE)

ggsave("./pictures/noafa1CT_fc.png", noafa1CT_fc, width = 11, height = 7, dpi = "print")
```

EXPERIMENT 1 MANIPULATED VS EXPERIMENT 2 MANIPULATED

```{r, include = FASE}
exp12anterior_frontal <- ggarrange(
  bae(elec = "AF7", type = "EXP12", labels = TRUE),
  bae(elec = "AF8", type = "EXP12"),
  bae(elec = "F7", type = "EXP12"),
  bae(elec = "F8", type = "EXP12"),
  bae(elec = "F3", type = "EXP12"),
  bae(elec = "F4", type = "EXP12"),
  nrow = 3, ncol = 2,
  common.legend =  TRUE)

exp12anterior_frontal
ggsave("./pictures/exp12anterior_frontal.png", exp12anterior_frontal, width = 9, height = 10, dpi = "print")

exp12fronto_central <- ggarrange( 
  bae(elec = "FT7", type = "EXP12", labels = TRUE),
  bae(elec = "FT8", type = "EXP12"),
  bae(elec = "T7", type = "EXP12"),
  bae(elec = "T8", type = "EXP12"),
  bae(elec = "C3", type = "EXP12"),
  bae(elec = "C4", type = "EXP12"),
  nrow = 3, ncol = 2,
  common.legend =  TRUE)

exp12fronto_central
ggsave("./pictures/exp12fronto_central.png", exp12fronto_central, width = 9, height = 10, dpi = "print")
```


```{r}
theme_topo <- function(base_size = 12)
  {theme_bw(base_size = base_size) %+replace% theme(rect = element_blank(), line = element_blank(), axis.text = element_blank(), axis.title = element_blank())}

circleFun <- function(center = c(0,0), diameter = 1, npoints = 100) {
  r = diameter / 2
  tt <- seq(0,2 * pi, length.out = npoints)
  xx <- center[1] + r * cos(tt)
  yy <- center[2] + r * sin(tt)
  return(data.frame(x = xx, y = yy)) }

headShape <- circleFun(c(0, 0), round(max(electrodeLocs$x)), npoints = 100) 
nose <- data.frame(x = c(-0.075, 0, .075), y=c(.495, .575, .495))
```

Function to create scalp plots with data at a given time point. Change electrode and timepoint at the bottom of the chunk to see different results. 

```{r}
int_scalp_plot <- function(TP, cond = "control") {
  singleTimepoint <- filter(ERP, time == TP & condition == cond)
  gridRes <- 124

  tmpTopo <- with(singleTimepoint, interp(x = x, y = y, z = amplitude.mean, xo = seq(min(x)*2, max(x)*2, length = gridRes), yo = seq(min(y)*2, max(y)*2, length = gridRes), linear = FALSE, extrap = TRUE, duplicate = TRUE))

  interpTopo <- data.frame(x = tmpTopo$x, tmpTopo$z)
  names(interpTopo)[1:length(tmpTopo$y)+1] <- tmpTopo$y
  interpTopo <- gather(interpTopo, key = y, value = amplitude.mean, -x, convert = TRUE)
  interpTopo$incircle <- sqrt(interpTopo$x^2 + interpTopo$y^2) < .7 
  interpTopo <- interpTopo[interpTopo$incircle,] 
  maskRing <- circleFun(diameter = 1.42) 

  ScalpPlotT <- ggplot(interpTopo, aes(x = x, y = y, fill = amplitude.mean)) +
    geom_raster() +
    stat_contour(aes(z = amplitude.mean, linetype = ..level..<0), colour = "black", size = 0.8, show.legend = FALSE) +
    theme_topo() +
    scale_fill_viridis(option = "plasma", limits = c(-1,3), guide = "colorbar", oob = squish) +
    geom_path(data = maskRing, aes(x, y, z = NULL, fill =NULL), colour = "white", size = 6) +
    geom_point(data = singleTimepoint, aes(x, y), size = 1) +
    geom_path(data = headShape, aes(x, y, z = NULL, fill = NULL), size = 1.5) +
    geom_path(data = nose, aes(x, y, z = NULL, fill = NULL), size = 1.5) +
    #ggtitle(paste0(cond)) +
    coord_fixed() +
    theme(plot.title = element_text(hjust = 0.5, lineheight = 0.5))
  return(ScalpPlotT) }

int_compare_scalps <- function(timepoint = 300, CT = TRUE) {
  
  if (CT == TRUE) {
    
    control_map <- int_scalp_plot(TP = timepoint, cond = "control") 
    target_map <- int_scalp_plot(TP = timepoint, cond = "target")

    final_plot <- ggarrange(
      target_map + ggtitle("Manipulated"),
      control_map + ggtitle("Standard"),
      common.legend = TRUE) }
  
  else {
    
    first_map <- int_scalp_plot(TP = timepoint, cond = "first_syllable")
    second_map <- int_scalp_plot(TP = timepoint, cond = "second_syllable")
    third_map <- int_scalp_plot(TP = timepoint, cond = "third_syllable")
    
    final_plot <- ggarrange(
      first_map + ggtitle("First syllable"),
      second_map + ggtitle("Second syllable"),
      third_map + ggtitle("Third syllable"),
      common.legend = TRUE, nrow = 1) }

return(final_plot) }

int_compare_scalps(250)
int_compare_scalps(250, CT = FALSE)

#ggsave("./pictures/p3_scalp.png", p3, width = 9, height = 5, dpi = "print")
```
